from __future__ import annotations

import base64
import re
from contextlib import AbstractContextManager
from pathlib import Path
from typing import NamedTuple, Protocol, cast

from graphviz import Digraph

from src.domain.design import (
    AzureServiceMapping,
    DesignComponent,
    DiagramMetadata,
    SystemDesignArtifact,
)
from src.domain.errors import DiagramGenerationError
from src.infrastructure.icons import (
    actor_icon_path,
    component_icon_path,
    dependency_icon_path,
)


class GraphRenderer(Protocol):
    """Minimal interface required from a Graphviz graph (or subgraph)."""

    def node(
        self,
        name: str,
        label: str,
        **attrs: str,
    ) -> None:
        """Add a node to the graph."""
        ...

    def edge(
        self,
        source: str,
        target: str,
        label: str,
        **attrs: str,
    ) -> None:
        """Add an edge to the graph."""
        ...

    def attr(
        self,
        *args: str,
        **attrs: str,
    ) -> None:
        """Set a graph/node/edge default attribute."""
        ...

    def subgraph(
        self, name: str | None = None
    ) -> AbstractContextManager[GraphRenderer]:
        """Open a subgraph, e.g. to force a shared rank or (when `name`
        starts with ``"cluster"``) to render a labeled, boxed group."""
        ...

    def pipe(self, format: str) -> bytes:
        """Render the graph."""
        ...


class _DiagramNode(NamedTuple):
    """One component, actor, external dependency, or supporting Azure
    service to place via `_lay_out_column`, already resolved to its icon
    (see `app/design/icons.py`).

    ``node_id`` is deliberately the SAME id across both the Logical
    Architecture Diagram and the Azure Service Mapping Diagram (a
    component's ``id``, an actor's ``id``, an external dependency's
    ``id``, or a supporting service's ``id``) - that shared id is the
    entire traceability mechanism between the two diagrams: a reviewer
    who spots ``C-003`` on one can find the identical ``C-003`` on the
    other.
    """

    node_id: str
    name: str
    tooltip: str
    icon_path: str
    # "" for a normal component caption; a color name (e.g.
    # "darkgoldenrod") to visually set an external dependency (or
    # supporting service) node's caption apart from a component's, since
    # both now render as icon nodes with no background fill to otherwise
    # tell them apart at a glance.
    caption_color: str = ""
    # An optional extra caption line (e.g. "Zone: Private VNet", or an
    # Azure service name) rendered under the name - never color alone,
    # per the accessibility requirement that boundary/category
    # information must be legible as text, not just inferred from a
    # border or fill color.
    footer: str = ""


# Matches the `xlink:href="...png"` (or `href="...png"` on newer
# SVG/Graphviz versions) that Graphviz writes for every node's
# `image=...png` HTML-label attribute - see `_inline_local_images`.
_LOCAL_IMAGE_HREF_PATTERN = re.compile(r'((?:xlink:href|href))="([^"]+\.png)"')

_ACTORS_DOMAIN = "Actors"
_EXTERNAL_DEPENDENCIES_DOMAIN = "External Dependencies"
_SUPPORTING_SERVICES_DOMAIN = "Supporting Azure Services"


class _DiagramBase:
    """Shared rendering primitives for both the Logical Architecture
    Diagram and the Azure Service Mapping Diagram.

    Neither diagram is generated by this class directly - see
    `ArchitectureDiagramGenerator.generate_logical`/`.generate_azure_mapping`
    below - this only holds the Graphviz plumbing (much of it hard-won;
    see each method's own docstring) that both renderers need
    byte-for-byte identically so the two diagrams share one consistent
    visual taxonomy, per the architecture-generation consistency
    requirement.
    """

    # Past this many total real edges (interfaces + dependency/
    # supporting-service edges combined), rendering every single one's
    # name as inline label text turns into unreadable clutter - dozens
    # of small text strings scattered across the diagram. Full detail is
    # still available via each edge's `tooltip` (shown on hover, and
    # already relied on by the frontend's DiagramViewer), so above this
    # threshold inline labels are dropped entirely rather than made
    # illegibly small.
    MAX_LABELED_EDGES = 24

    # Domain shown for a component whose `domain` field is blank -
    # keeps older/unclassified designs (and anything that constructs a
    # `DesignComponent` without a domain) rendering as a single grouped
    # cluster instead of erroring or silently omitting the field.
    DEFAULT_DOMAIN = "Other Components"

    # Side length, in points, of a node's icon image within its
    # HTML-like label - see `_node_label`.
    ICON_SIZE_PX = 56

    # Caption color for an external dependency node, set apart from a
    # component's default (unset -> black) caption color.
    DEPENDENCY_CAPTION_COLOR = "darkgoldenrod"

    # Caption color for a supporting Azure service node (identity,
    # networking, secrets, monitoring, CI/CD) - distinct from both a
    # component's default and an external dependency's, so all three
    # node families stay visually distinguishable without relying on
    # icon shape alone.
    SUPPORTING_SERVICE_CAPTION_COLOR = "steelblue"

    def _create_graph(self, output_format: str = "svg") -> GraphRenderer:
        """Build an empty, styled ``Digraph`` ready for nodes/edges.

        ``output_format`` only ever changes which raster/vector format
        ``graph.pipe`` produces later - every attribute set here is
        identical either way, since it's all layout/styling, none of it
        format-specific.
        """
        graph = Digraph(
            name="architecture_diagram",
            format=output_format,
        )

        # No fixed page size or `ratio="compress"` here: forcing a
        # multi-domain, many-edge diagram into one Letter page squeezes
        # an already-complex layout into a small bounding box, which
        # stretches and bends edges into long arcs. The frontend's
        # DiagramViewer already supports zoom/pan, so letting Graphviz
        # size the SVG naturally - as large as the actual content needs
        # - produces straighter, more readable edges at the cost of not
        # fitting on one printed page unscaled.
        #
        # `rankdir="LR"` (left-to-right) rather than top-to-bottom,
        # matching the flow direction of a typical reference cloud
        # architecture diagram (client -> gateway -> services -> data
        # stores). `nodesep`/`ranksep` are larger than plain-box-node
        # defaults would need, to leave room for each edge's inline
        # label node (see `_add_labeled_edge`) to sit clear of the
        # icon-and-caption nodes on either side of it.
        graph.attr(
            rankdir="LR",
            bgcolor="white",
            pad="0.3",
            nodesep="0.5",
            ranksep="0.9",
            # Right-angle, straight-segment edge routing instead of
            # Graphviz's default curved splines - reads as far less
            # "haphazard" for a boxes-and-arrows architecture diagram,
            # and was stress-tested at large component/interface counts
            # without reproducing the `dot` crash discussed on
            # `_lay_out_column`.
            splines="ortho",
            labelloc="t",
            labeljust="l",
            fontname="Helvetica",
        )

        # `shape="none"` - every node supplies its own HTML-like label
        # (see `_node_label`), which lays out the icon and caption
        # itself; a `box`/`filled` default here would just draw an
        # unused outline behind it.
        graph.attr(
            "node",
            shape="none",
            fontname="Helvetica",
            fontsize="11",
        )

        graph.attr(
            "edge",
            color="gray40",
            fontname="Helvetica",
            fontsize="9",
            arrowsize="0.7",
        )

        return cast(GraphRenderer, graph)

    @staticmethod
    def _inline_local_images(svg: str) -> str:
        """Replace every local-filesystem PNG `href`/`xlink:href` that
        Graphviz wrote for a node's icon with an inline base64 `data:`
        URI.

        Graphviz's SVG output references an icon by the exact filesystem
        path passed to its `IMG SRC=...` HTML-label attribute - fine for
        a `dot`-produced file sitting next to that path, but this SVG is
        persisted as a Blob artifact and later rendered directly in a
        browser (`DiagramViewer.tsx`), which has no access to this
        server's filesystem. Inlining the icon bytes keeps the SVG fully
        self-contained wherever it ends up.
        """

        def _inline(match: re.Match[str]) -> str:
            attribute, path = match.group(1), match.group(2)
            encoded = base64.b64encode(Path(path).read_bytes()).decode("ascii")
            return f'{attribute}="data:image/png;base64,{encoded}"'

        return _LOCAL_IMAGE_HREF_PATTERN.sub(_inline, svg)

    @staticmethod
    def _escape_html(text: str) -> str:
        """Escape the handful of characters that are structurally
        significant inside a Graphviz HTML-like label - see
        `_node_label`/`_metadata_label`. Every piece of text placed into
        one of these labels is free text (LLM- or user-supplied), so an
        unescaped `<`, `>`, or `&` would otherwise corrupt the label's
        HTML structure."""

        return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    @classmethod
    def _node_label(cls, node: _DiagramNode) -> str:
        """Build the HTML-like label Graphviz needs to place `node`'s
        icon above its "{id}\\n{name}" caption (and optional footer
        line) without the two overlapping.

        A plain `image=...` + `label=...` pair on a `shape="none"` node
        does NOT reserve separate space for the label under the
        installed Graphviz build (2.43.0): the label text renders
        overlapping the image's own area instead of below it, regardless
        of `labelloc`. An HTML-like label with the image and caption in
        stacked table rows lays out exactly as expected - confirmed
        visually against the alternative before choosing this approach.
        """

        size = cls.ICON_SIZE_PX
        node_id = cls._escape_html(node.node_id)
        name = cls._escape_html(node.name)

        caption = f"{node_id}<BR/>{name}"
        if node.caption_color:
            caption = f'<FONT COLOR="{node.caption_color}">{caption}</FONT>'

        footer_row = ""
        if node.footer:
            footer_text = cls._escape_html(node.footer)
            footer_row = (
                '<TR><TD><FONT POINT-SIZE="9" COLOR="gray30">'
                f"{footer_text}</FONT></TD></TR>"
            )

        return (
            '<<TABLE BORDER="0" CELLBORDER="0" CELLSPACING="2">'
            f'<TR><TD FIXEDSIZE="TRUE" WIDTH="{size}" HEIGHT="{size}">'
            f'<IMG SRC="{node.icon_path}" SCALE="TRUE"/></TD></TR>'
            f"<TR><TD>{caption}</TD></TR>"
            f"{footer_row}"
            "</TABLE>>"
        )

    @classmethod
    def _lay_out_column(
        cls,
        graph: GraphRenderer,
        nodes: list[_DiagramNode],
    ) -> None:
        """Place `nodes` into `graph` (a cluster subgraph) as a single
        top-to-bottom column, in `nodes`' order.

        Consecutive nodes are chained with an invisible, unlabeled,
        heavily-weighted edge - a normal *directed* edge, contributing a
        real (if fake) rank-ordering constraint, NOT a `rank=same`
        ("flat"/same-rank) edge. That distinction matters: nesting
        `rank=same` inside a Graphviz cluster, on a graph with enough
        real edges crossing between clusters, reliably crashes the
        installed Graphviz `dot` build (2.43.0) with
        `class2.c:148: merge_chain: Assertion 'ED_to_virt(e) == NULL'
        failed`, confirmed via local reproduction at roughly 40+
        components / 60+ interfaces spread across several domains - well
        within what a real generated architecture can reach. Directed
        (non-flat) invisible edges inside a cluster, at the same or
        greater scale, do not trigger it.
        """

        previous_id: str | None = None

        for node in nodes:
            graph.node(
                node.node_id,
                label=cls._node_label(node),
                tooltip=node.tooltip,
            )

            if previous_id is not None:
                graph.edge(
                    previous_id, node.node_id, label="", style="invis", weight="4"
                )

            previous_id = node.node_id

    @classmethod
    def _add_cluster(
        cls,
        graph: GraphRenderer,
        cluster_name: str,
        label: str,
        border_color: str,
        nodes: list[_DiagramNode],
    ) -> None:
        if not nodes:
            return

        with graph.subgraph(name=cluster_name) as cluster:
            cluster.attr(
                label=label,
                style="dashed",
                color=border_color,
                fontname="Helvetica-Bold",
                fontsize="12",
                bgcolor="white",
            )
            cls._lay_out_column(cluster, nodes)

    @staticmethod
    def _domain_of(component: DesignComponent) -> str:
        return component.domain.strip() or _DiagramBase.DEFAULT_DOMAIN

    @classmethod
    def _group_by_domain(
        cls,
        components: list[DesignComponent],
    ) -> dict[str, list[DesignComponent]]:
        """Bucket `components` by domain, preserving each domain's first
        appearance order (Python dicts preserve insertion order) - so
        clusters render in roughly the order the design introduced them,
        rather than an arbitrary or alphabetical order."""

        grouped: dict[str, list[DesignComponent]] = {}

        for component in components:
            grouped.setdefault(cls._domain_of(component), []).append(component)

        return grouped

    @classmethod
    def _add_labeled_edge(
        cls,
        graph: GraphRenderer,
        *,
        source: str,
        target: str,
        label_id: str,
        label_text: str,
        tooltip: str,
        constraint: str,
        style: str = "solid",
        color: str = "gray40",
        arrowhead: str = "normal",
    ) -> None:
        """Draw a single directed connection from ``source`` to
        ``target``, optionally with a name shown along the way.

        Splits the edge into ``source -> label node -> target`` when a
        label is present (a borderless `shape="plaintext"` node holding
        just the text) rather than using Graphviz's own `xlabel`: with
        `rankdir="LR"` the installed `dot` (2.42/2.43) drops or
        overlaps every exterior label on non-trivial diagrams - see git
        history for the empirical repro. The label node gets a real
        inbound/outbound edge segment, so it's unambiguously "this
        edge's name" rather than a floating annotation, and `dot`
        reserves real layout space for it like any other node.
        """

        if not label_text:
            graph.edge(
                source,
                target,
                label="",
                tooltip=tooltip,
                style=style,
                color=color,
                constraint=constraint,
                arrowhead=arrowhead,
            )
            return

        graph.node(
            label_id,
            label_text,
            shape="plaintext",
            fontname="Helvetica",
            fontsize="9",
            fontcolor=color,
            margin="0.02,0.02",
            tooltip=tooltip,
        )

        graph.edge(
            source,
            label_id,
            label="",
            tooltip=tooltip,
            style=style,
            color=color,
            arrowhead="none",
            constraint=constraint,
        )
        graph.edge(
            label_id,
            target,
            label="",
            tooltip=tooltip,
            style=style,
            color=color,
            arrowhead=arrowhead,
            constraint=constraint,
        )

    @classmethod
    def _metadata_label(
        cls,
        metadata: DiagramMetadata,
        legend_rows: list[tuple[str, str]],
    ) -> str:
        """Build the graph-level HTML label carrying the required
        diagram metadata block (Title/Description/Scope/Author/Version/
        Last Updated/External References) plus a legend explaining this
        diagram's notation - both required by the architecture-
        generation phase's diagram-metadata and accessibility rules.

        Rendered via ``graph.attr(label=...)`` with ``labelloc="t"`` (set
        in ``_create_graph``), so it always sits at the top of the
        diagram rather than needing per-node placement.
        """

        esc = cls._escape_html

        references = (
            "; ".join(esc(reference) for reference in metadata.external_references)
            or "TBD"
        )

        legend_html = "".join(
            f'<TR><TD ALIGN="LEFT"><FONT POINT-SIZE="9">{esc(swatch)}'
            f"  {esc(description)}</FONT></TD></TR>"
            for swatch, description in legend_rows
        )

        return (
            '<<TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="3">'
            '<TR><TD ALIGN="LEFT"><FONT POINT-SIZE="16"><B>'
            f"{esc(metadata.title)}</B></FONT></TD></TR>"
            f'<TR><TD ALIGN="LEFT"><FONT POINT-SIZE="10">{esc(metadata.description)}'
            "</FONT></TD></TR>"
            '<TR><TD ALIGN="LEFT"><FONT POINT-SIZE="9" COLOR="gray30">'
            f"Scope: {esc(metadata.scope)} &#160;|&#160; "
            f"Author: {esc(metadata.author)} &#160;|&#160; "
            f"Version: {metadata.version} &#160;|&#160; "
            f"Last updated: {esc(metadata.last_updated)} &#160;|&#160; "
            f"References: {references}"
            "</FONT></TD></TR>"
            f"{legend_html}"
            "</TABLE>>"
        )


class ArchitectureDiagramGenerator(_DiagramBase):
    """Generate the two complementary architecture diagrams required by
    the architecture-generation phase, as SVG (and PNG, for embedding in
    the exported technical design ``.docx``).

    The concrete ``app.application.ports.DiagramRendererPort``
    implementation - satisfied structurally via its
    ``generate_logical``/``generate_azure_mapping`` methods, no
    inheritance required.

    1. ``generate_logical`` - the Logical Architecture Diagram:
       technology-agnostic components, actors, and their interactions/
       trust boundaries. Never shows an Azure icon or Azure service name.
    2. ``generate_azure_mapping`` - the Azure Service Mapping Diagram:
       every major logical component/actor/external dependency mapped to
       its concrete Azure service(s), plus supporting Azure services
       (identity, networking, secrets, monitoring, CI/CD) that don't map
       1:1 to any single component.

    Both diagrams use the SAME node ids (a component's/actor's/external
    dependency's own ``id``) and the SAME domain-clustering/edge-styling
    conventions, so a reviewer can trace any node from one diagram to
    the identically-labeled node on the other - the architecture-
    generation phase's core traceability requirement.
    """

    # -- Logical Architecture Diagram ----------------------------------

    def generate_logical(
        self,
        design: SystemDesignArtifact,
        metadata: DiagramMetadata,
    ) -> str:
        """Render the technology-agnostic Logical Architecture Diagram."""

        try:
            graph = self._build_logical_graph(design, "svg", metadata)
            svg = graph.pipe(format="svg").decode("utf-8")
            return self._inline_local_images(svg)
        except Exception as exc:
            raise DiagramGenerationError(
                "Logical architecture diagram generation failed."
            ) from exc

    def generate_logical_png(
        self,
        design: SystemDesignArtifact,
        metadata: DiagramMetadata,
    ) -> bytes:
        """The raster analogue of ``generate_logical``, for embedding in
        the exported technical design ``.docx`` (python-docx's
        ``add_picture`` needs a raster format, and cannot embed SVG)."""

        try:
            graph = self._build_logical_graph(design, "png", metadata)
            return graph.pipe(format="png")
        except Exception as exc:
            raise DiagramGenerationError(
                "Logical architecture diagram generation failed."
            ) from exc

    def _build_logical_graph(
        self,
        design: SystemDesignArtifact,
        output_format: str,
        metadata: DiagramMetadata,
    ) -> GraphRenderer:
        graph = self._create_graph(output_format)

        legend = [
            ("[icon+box]", "Logical component (technology-agnostic)"),
            (
                "[icon+box, italic footer]",
                "Trust/security zone, shown as text - never color alone",
            ),
            ("solid arrow ->", "Synchronous request/response interaction"),
            ("dashed arrow ->", "Asynchronous event/message interaction"),
            ("goldenrod dashed ->", "Use of an external dependency"),
        ]
        graph.attr(label=self._metadata_label(metadata, legend))

        domain_of = self._add_components(graph, design)
        self._add_actors(graph, design)
        self._add_external_dependencies(graph, design)

        total_edges = len(design.interfaces) + sum(
            len(dependency.used_by_components)
            for dependency in design.external_dependencies
        )
        suppress_labels = total_edges > self.MAX_LABELED_EDGES

        self._add_interfaces(graph, design, domain_of, suppress_labels)
        self._add_dependency_edges(graph, design, suppress_labels)

        return graph

    def _add_components(
        self,
        graph: GraphRenderer,
        design: SystemDesignArtifact,
    ) -> dict[str, str]:
        # Returns component id -> domain, so `_add_interfaces` can tell
        # whether an interface stays within one domain (and can safely
        # be allowed to influence layout) or crosses domains.
        domain_of: dict[str, str] = {}

        grouped = self._group_by_domain(design.components)

        for index, (domain, components) in enumerate(grouped.items()):
            nodes = [
                _DiagramNode(
                    node_id=component.id,
                    name=component.name,
                    tooltip=component.responsibility,
                    icon_path=component_icon_path(
                        component.name, component.responsibility
                    ),
                    footer=(
                        f"Zone: {component.trust_zone}"
                        if component.trust_zone and component.trust_zone != "TBD"
                        else ""
                    ),
                )
                for component in components
            ]

            for component in components:
                domain_of[component.id] = domain

            self._add_cluster(
                graph, f"cluster_domain_{index}", domain, "#666666", nodes
            )

        return domain_of

    def _add_actors(self, graph: GraphRenderer, design: SystemDesignArtifact) -> None:
        if not design.actors:
            return

        nodes = [
            _DiagramNode(
                node_id=actor.id,
                name=actor.name,
                tooltip=actor.description,
                icon_path=actor_icon_path(actor.kind),
                footer=f"Actor ({actor.kind})",
            )
            for actor in design.actors
        ]

        self._add_cluster(graph, "cluster_actors", _ACTORS_DOMAIN, "#666666", nodes)

    def _add_external_dependencies(
        self,
        graph: GraphRenderer,
        design: SystemDesignArtifact,
    ) -> None:
        nodes = [
            _DiagramNode(
                node_id=dependency.id,
                name=dependency.name,
                tooltip=dependency.purpose,
                icon_path=dependency_icon_path(dependency.name, dependency.purpose),
                caption_color=self.DEPENDENCY_CAPTION_COLOR,
            )
            for dependency in design.external_dependencies
        ]

        self._add_cluster(
            graph,
            "cluster_external_dependencies",
            _EXTERNAL_DEPENDENCIES_DOMAIN,
            "darkgoldenrod",
            nodes,
        )

    def _add_interfaces(
        self,
        graph: GraphRenderer,
        design: SystemDesignArtifact,
        domain_of: dict[str, str],
        suppress_labels: bool,
    ) -> None:
        for interface in design.interfaces:
            same_domain = domain_of.get(interface.source_component) == domain_of.get(
                interface.target_component
            )

            is_async = interface.flow_type == "async"
            label_text = ""
            if not suppress_labels:
                kind_marker = "event" if is_async else "request"
                label_text = f"{interface.name} ({kind_marker})"

            self._add_labeled_edge(
                graph,
                source=interface.source_component,
                target=interface.target_component,
                label_id=f"__label__{interface.id}",
                label_text=label_text,
                tooltip=f"{interface.purpose} [{interface.flow_type}]",
                # An interface within a single domain cluster is allowed
                # to influence layout. One that crosses domains keeps
                # `constraint="false"` so a cross-domain edge doesn't
                # fight the clusters' own rank assignment.
                constraint="true" if same_domain else "false",
                style="dashed" if is_async else "solid",
                arrowhead="vee" if is_async else "normal",
            )

    def _add_dependency_edges(
        self,
        graph: GraphRenderer,
        design: SystemDesignArtifact,
        suppress_labels: bool,
    ) -> None:
        for dependency in design.external_dependencies:
            for position, component_id in enumerate(dependency.used_by_components):
                # Only the first edge into a given dependency shows its
                # name as an inline label; a dependency used by several
                # components would otherwise repeat the exact same label
                # text on every incoming edge.
                show_label = not suppress_labels and position == 0

                self._add_labeled_edge(
                    graph,
                    source=component_id,
                    target=dependency.id,
                    label_id=f"__label__{dependency.id}__{component_id}",
                    label_text=dependency.name if show_label else "",
                    tooltip=dependency.purpose,
                    style="dashed",
                    color="darkgoldenrod",
                    arrowhead="vee",
                    # Dependencies aren't clustered per-domain, so letting
                    # these edges influence rank assignment would pull a
                    # dependency's rank toward whichever component
                    # happened to be laid out last among potentially
                    # several unrelated domains.
                    constraint="false",
                )

    # -- Azure Service Mapping Diagram ---------------------------------

    def generate_azure_mapping(
        self,
        design: SystemDesignArtifact,
        metadata: DiagramMetadata,
    ) -> str:
        """Render the Azure Service Mapping Diagram."""

        try:
            graph = self._build_azure_graph(design, "svg", metadata)
            svg = graph.pipe(format="svg").decode("utf-8")
            return self._inline_local_images(svg)
        except Exception as exc:
            raise DiagramGenerationError(
                "Azure service mapping diagram generation failed."
            ) from exc

    def generate_azure_mapping_png(
        self,
        design: SystemDesignArtifact,
        metadata: DiagramMetadata,
    ) -> bytes:
        """The raster analogue of ``generate_azure_mapping``, for
        embedding in the exported technical design ``.docx``."""

        try:
            graph = self._build_azure_graph(design, "png", metadata)
            return graph.pipe(format="png")
        except Exception as exc:
            raise DiagramGenerationError(
                "Azure service mapping diagram generation failed."
            ) from exc

    def _build_azure_graph(
        self,
        design: SystemDesignArtifact,
        output_format: str,
        metadata: DiagramMetadata,
    ) -> GraphRenderer:
        graph = self._create_graph(output_format)

        legend = [
            (
                "[Azure icon+box]",
                "Official Azure service implementing a logical component",
            ),
            (
                "[Azure icon+box, blue caption]",
                "Supporting Azure service (identity/network/secrets/monitoring/CI-CD)",
            ),
            ("footer text", "Connectivity / trust zone - never color alone"),
            ("solid arrow ->", "Synchronous request/response"),
            ("dashed arrow ->", "Asynchronous event/message"),
            (
                "steelblue dashed ->",
                '"supports" relationship from a supporting service',
            ),
            (
                "Node id matches the Logical Architecture Diagram",
                "use it to trace a component to its Azure implementation",
            ),
        ]
        graph.attr(label=self._metadata_label(metadata, legend))

        domain_of = self._domain_lookup(design)
        mapping_by_component = self._group_mappings_by_component(design.azure_mappings)

        self._add_mapped_nodes(graph, design, domain_of, mapping_by_component)
        self._add_supporting_services(graph, design)

        total_edges = len(design.interfaces) + sum(
            len(dependency.used_by_components)
            for dependency in design.external_dependencies
        )
        suppress_labels = total_edges > self.MAX_LABELED_EDGES

        self._add_interfaces_for_mapped(graph, design, domain_of, suppress_labels)
        self._add_dependency_edges_for_mapped(graph, design, suppress_labels)
        self._add_supporting_edges(graph, design, suppress_labels)

        return graph

    @staticmethod
    def _domain_lookup(design: SystemDesignArtifact) -> dict[str, str]:
        """Every node id's domain/pseudo-domain, shared between the
        Logical and Azure diagrams so clusters line up the same way in
        both - components keep their real ``domain``, while actors and
        external dependencies get the same fixed pseudo-domains the
        Logical diagram already clusters them under."""

        lookup: dict[str, str] = {}

        for component in design.components:
            lookup[component.id] = _DiagramBase._domain_of(component)

        for actor in design.actors:
            lookup[actor.id] = _ACTORS_DOMAIN

        for dependency in design.external_dependencies:
            lookup[dependency.id] = _EXTERNAL_DEPENDENCIES_DOMAIN

        return lookup

    @staticmethod
    def _group_mappings_by_component(
        mappings: list[AzureServiceMapping],
    ) -> dict[str, list[AzureServiceMapping]]:
        grouped: dict[str, list[AzureServiceMapping]] = {}
        for mapping in mappings:
            grouped.setdefault(mapping.component_id, []).append(mapping)
        return grouped

    def _add_mapped_nodes(
        self,
        graph: GraphRenderer,
        design: SystemDesignArtifact,
        domain_of: dict[str, str],
        mapping_by_component: dict[str, list[AzureServiceMapping]],
    ) -> None:
        """One node per component/actor/external dependency that has at
        least one Azure Service Mapping entry, grouped into the same
        domain clusters `_domain_lookup` assigned - anything with NO
        mapping entry is intentionally omitted from this diagram (it has
        nothing to show here yet), rather than rendered as an
        empty/placeholder Azure node.
        """

        display_name_by_id = {
            component.id: component.name for component in design.components
        }
        display_name_by_id.update({actor.id: actor.name for actor in design.actors})
        display_name_by_id.update(
            {
                dependency.id: dependency.name
                for dependency in design.external_dependencies
            }
        )

        nodes_by_domain: dict[str, list[_DiagramNode]] = {}

        for component_id, mappings in mapping_by_component.items():
            domain = domain_of.get(component_id, self.DEFAULT_DOMAIN)
            service_names = " + ".join(mapping.azure_service for mapping in mappings)
            primary = mappings[0]

            footer_parts = [
                part
                for part in (
                    (
                        f"Connectivity: {primary.connectivity}"
                        if primary.connectivity and primary.connectivity != "TBD"
                        else ""
                    ),
                    (
                        f"Zone: {primary.trust_zone}"
                        if primary.trust_zone and primary.trust_zone != "TBD"
                        else ""
                    ),
                )
                if part
            ]

            icon_path = component_icon_path(service_names, primary.rationale)

            node = _DiagramNode(
                node_id=component_id,
                name=service_names,
                tooltip=(
                    f"{display_name_by_id.get(component_id, component_id)} -> "
                    f"{service_names}. {primary.rationale}"
                ),
                icon_path=icon_path,
                footer=" | ".join(footer_parts),
            )
            nodes_by_domain.setdefault(domain, []).append(node)

        for index, (domain, nodes) in enumerate(nodes_by_domain.items()):
            border = (
                "darkgoldenrod"
                if domain == _EXTERNAL_DEPENDENCIES_DOMAIN
                else "#0078D4"
            )
            self._add_cluster(
                graph, f"cluster_azure_domain_{index}", domain, border, nodes
            )

    def _add_supporting_services(
        self, graph: GraphRenderer, design: SystemDesignArtifact
    ) -> None:
        if not design.supporting_azure_services:
            return

        nodes = [
            _DiagramNode(
                node_id=service.id,
                name=service.azure_service,
                tooltip=f"{service.category}: {service.purpose}. {service.rationale}",
                icon_path=component_icon_path(service.azure_service, service.purpose),
                caption_color=self.SUPPORTING_SERVICE_CAPTION_COLOR,
                footer=service.category,
            )
            for service in design.supporting_azure_services
        ]

        self._add_cluster(
            graph,
            "cluster_supporting_services",
            _SUPPORTING_SERVICES_DOMAIN,
            "steelblue",
            nodes,
        )

    def _add_interfaces_for_mapped(
        self,
        graph: GraphRenderer,
        design: SystemDesignArtifact,
        domain_of: dict[str, str],
        suppress_labels: bool,
    ) -> None:
        mapped_ids = {mapping.component_id for mapping in design.azure_mappings}

        for interface in design.interfaces:
            if (
                interface.source_component not in mapped_ids
                or interface.target_component not in mapped_ids
            ):
                # Only draw an edge between two nodes that both actually
                # exist on this diagram (i.e. both have an Azure
                # mapping) - an edge to a node this diagram omitted would
                # otherwise implicitly (and wrongly) create it.
                continue

            same_domain = domain_of.get(interface.source_component) == domain_of.get(
                interface.target_component
            )
            is_async = interface.flow_type == "async"
            label_text = "" if suppress_labels else interface.name

            self._add_labeled_edge(
                graph,
                source=interface.source_component,
                target=interface.target_component,
                label_id=f"__azure_label__{interface.id}",
                label_text=label_text,
                tooltip=f"{interface.purpose} [{interface.flow_type}]",
                constraint="true" if same_domain else "false",
                style="dashed" if is_async else "solid",
                arrowhead="vee" if is_async else "normal",
            )

    def _add_dependency_edges_for_mapped(
        self,
        graph: GraphRenderer,
        design: SystemDesignArtifact,
        suppress_labels: bool,
    ) -> None:
        mapped_ids = {mapping.component_id for mapping in design.azure_mappings}

        for dependency in design.external_dependencies:
            if dependency.id not in mapped_ids:
                continue

            for position, component_id in enumerate(dependency.used_by_components):
                if component_id not in mapped_ids:
                    continue

                show_label = not suppress_labels and position == 0

                self._add_labeled_edge(
                    graph,
                    source=component_id,
                    target=dependency.id,
                    label_id=f"__azure_label__{dependency.id}__{component_id}",
                    label_text=dependency.name if show_label else "",
                    tooltip=dependency.purpose,
                    style="dashed",
                    color="darkgoldenrod",
                    arrowhead="vee",
                    constraint="false",
                )

    def _add_supporting_edges(
        self,
        graph: GraphRenderer,
        design: SystemDesignArtifact,
        suppress_labels: bool,
    ) -> None:
        mapped_ids = {mapping.component_id for mapping in design.azure_mappings}

        for service in design.supporting_azure_services:
            for position, component_id in enumerate(service.applies_to_components):
                if component_id not in mapped_ids:
                    continue

                show_label = not suppress_labels and position == 0

                self._add_labeled_edge(
                    graph,
                    source=service.id,
                    target=component_id,
                    label_id=f"__support_label__{service.id}__{component_id}",
                    label_text="supports" if show_label else "",
                    tooltip=f"{service.category}: {service.purpose}",
                    style="dashed",
                    color=self.SUPPORTING_SERVICE_CAPTION_COLOR,
                    arrowhead="diamond",
                    constraint="false",
                )
